server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  # datasource:
  #   url: ${DB_URL:jdbc:postgresql://localhost:5432/margi_mane}
  #   username: ${DB_USERNAME:postgres}
  #   password: ${DB_PASSWORD:postgres}

  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-fancy-paper-a4o49w04-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_jELthWH1p7ne}
    
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: ${FLYWAY_ENABLED:false}

app:
  admin:
    mobile: ${ADMIN_MOBILE:9886025999}
    password: ${ADMIN_PASSWORD:godisgreat}
  jwt:
    secret: ${JWT_SECRET:8dF3kL9xQ2mZ7vT1aR6yU4nH0cW5bE8sD3jX9kP2qL7tV1z}
    expiry-minutes: ${JWT_EXPIRY_MINUTES:1440}
  business:
    name: Margi Mane
    phone: ${BUSINESS_PHONE:+919886025999}
    maps-url: ${BUSINESS_MAPS_URL:https://maps.app.goo.gl/b8LTGr4MbHqsaasTA}
